USE ODS;

/*NO COMMENTS*/

ALTER TABLE ODS_HC_SERVICIOS ADD INDEX fk_ser_cli_idx (ID_CLIENTE ASC);
ALTER TABLE ODS_HC_SERVICIOS ADD CONSTRAINT fk_ser_cli FOREIGN KEY (ID_CLIENTE) REFERENCES ODS_HC_CLIENTES (ID_CLIENTE);

ALTER TABLE ODS_HC_SERVICIOS ADD INDEX fk_ser_dir_idx (ID_DIRECCION_SERVICIO ASC);
ALTER TABLE ODS_HC_SERVICIOS ADD CONSTRAINT fk_ser_dir FOREIGN KEY (ID_DIRECCION_SERVICIO) REFERENCES ODS_HC_DIRECCIONES (ID_DIRECCION);

ALTER TABLE ODS_HC_SERVICIOS ADD INDEX fk_ser_canales_idx (ID_CANAL ASC);
ALTER TABLE ODS_HC_SERVICIOS ADD CONSTRAINT fk_ser_canales FOREIGN KEY (ID_CANAL) REFERENCES ODS_DM_CANALES (ID_CANAL);

ALTER TABLE ODS_HC_SERVICIOS ADD INDEX fk_ser_productos_idx (ID_PRODUCTO ASC);
ALTER TABLE ODS_HC_SERVICIOS ADD CONSTRAINT fk_ser_productos FOREIGN KEY (ID_PRODUCTO) REFERENCES ODS_DM_PRODUCTOS (ID_PRODUCTO);

