USE ODS;

SELECT * FROM ODS_HC_SERVICIOS;

INSERT INTO ODS_DM_CANALES (DE_CANAL, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(CHANNEL)) , NOW(),NOW()
FROM STAGE.STG_PRODUCTOS_CRM
WHERE TRIM(CHANNEL)!='';                     COMMIT;
INSERT INTO ODS_DM_CANALES VALUES(999,'DESCONOCIDO',NOW(),NOW());              COMMIT;
ANALYZE TABLE ODS_DM_CANALES
;

INSERT INTO ODS_DM_PRODUCTOS (DE_PRODUCTO, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(PRODUCT_NAME)), NOW(),NOW()
FROM STAGE.STG_PRODUCTOS_CRM
WHERE TRIM(PRODUCT_NAME)!='';                    COMMIT;
INSERT INTO ODS_DM_PRODUCTOS VALUES(9999,'DESCONOCIDO',NOW(),NOW());                 COMMIT;
ANALYZE TABLE ODS_DM_PRODUCTOS
;

INSERT INTO ODS_HC_SERVICIOS (ID_CLIENTE,ID_PRODUCTO,PUNTO_ACCESO,ID_CANAL,ID_AGENTE,ID_DIRECCION_SERVICIO,FC_INICIO,FC_INSTALACION,FC_FIN,FC_INSERT,FC_MODIFICACION)
SELECT DIR.ID_CLIENTE
, PR1.ID_PRODUCTO
, CASE WHEN TRIM(ACCESS_POINT)!='' THEN UPPER(TRIM(ACCESS_POINT)) ELSE 'DESCONOCIDO' END PUNTO_ACCESO
, CAN.ID_CANAL
, CASE WHEN TRIM(AGENT_CODE)!='' THEN TRIM(UPPER(AGENT_CODE)) ELSE 99999 END ID_AGENTE
, DIR.ID_DIRECCION_CLIENTE
, CASE WHEN TRIM(START_DATE)!='' THEN STR_TO_DATE(START_DATE, '%d/%m/%Y') ELSE STR_TO_DATE('31/12/9999','%d/%m/%Y') END FC_INICIO
, CASE WHEN TRIM(INSTALL_DATE)!='' THEN STR_TO_DATE(REPLACE(MID(INSTALL_DATE,1,10),'-','/'), '%Y/%m/%d') ELSE STR_TO_DATE('31/12/9999','%d/%m/%Y') END FC_INSTALACION
, CASE WHEN TRIM(END_DATE)!='' THEN STR_TO_DATE(REPLACE(MID(END_DATE,1,10),'-','/'), '%Y/%m/%d') ELSE STR_TO_DATE('31/12/9999','%d/%m/%Y') END FC_FIN
, NOW() 
, STR_TO_DATE('31/12/9999','%d/%m/%Y')
FROM STAGE.STG_PRODUCTOS_CRM PR
INNER JOIN ODS_DM_PRODUCTOS PR1 ON CASE WHEN TRIM(PRODUCT_NAME)!='' THEN UPPER(TRIM(PRODUCT_NAME)) ELSE 'DESCONOCIDO' END=DE_PRODUCTO
INNER JOIN ODS_DM_CANALES CAN ON CASE WHEN TRIM(CHANNEL)!='' THEN TRIM(UPPER(CHANNEL)) ELSE 'DESCONOCIDO' END=CAN.DE_CANAL
INNER JOIN ODS_HC_CLIENTES DIR ON DIR.ID_CLIENTE=CUSTOMER_ID
; 

COMMIT; ANALYZE TABLE ODS_HC_SERVICIOS;



 