USE ODS; 

/*NO COMMENTS*/

INSERT INTO ODS_DM_METODOS_PAGO (DE_METODO_PAGO , FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(BILL_METHOD)), NOW(),NOW()
FROM STAGE.STG_FACTURAS_FCT
WHERE TRIM(BILL_METHOD)!='';
INSERT INTO ODS_DM_METODOS_PAGO VALUES(9999,'DESCONOCIDO',NOW(),NOW());
COMMIT;
ANALYZE TABLE ODS_DM_METODOS_PAGO
;

INSERT INTO ODS_DM_CICLOS_FACTURACION (DE_CICLO_FACTURACION , FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(BILL_CYCLE)), NOW(),NOW()
FROM STAGE.STG_FACTURAS_FCT
WHERE TRIM(BILL_CYCLE)!='';
INSERT INTO ODS_DM_METODOS_PAGO VALUES(999999,'DESCONOCIDO',NOW(),NOW());
COMMIT;
ANALYZE TABLE ODS_DM_CICLOS_FACTURACION
;


INSERT INTO ODS_HC_FACTURAS 
SELECT BILL_REF_NO AS ID_FACTURA
, CLI.ID_CLIENTE
, CASE WHEN TRIM(START_DATE)!='' THEN STR_TO_DATE(REPLACE(MID(START_DATE,1,10),'-','/'), '%Y/%m/%d') ELSE STR_TO_DATE('31/12/9999','%d/%m/%Y') END FC_INICIO
, CASE WHEN TRIM(END_DATE)!='' THEN STR_TO_DATE(REPLACE(END_DATE,'-','/'), '%Y/%m/%d') ELSE STR_TO_DATE('31/12/9999','%d/%m/%Y') END FC_FIN
, CASE WHEN TRIM(STATEMENT_DATE)!='' THEN STR_TO_DATE(REPLACE(MID(STATEMENT_DATE,1,10),'-','/'), '%Y/%m/%d') ELSE STR_TO_DATE('31/12/9999','%d/%m/%Y') END FC_ESTADO
, CASE WHEN TRIM(PAYMENT_DATE)!='' THEN STR_TO_DATE(REPLACE(MID(PAYMENT_DATE,1,10),'-','/'), '%Y/%m/%d') ELSE STR_TO_DATE('31/12/9999','%d/%m/%Y') END FC_PAGO
, CF.ID_CICLO_FACTURACION 
, MP.ID_METODO_PAGO
, CASE WHEN TRIM(AMOUNT)!='' THEN TRIM(UPPER(AMOUNT)) ELSE 000000000000 END CANTIDAD
, NOW() 
, STR_TO_DATE('31/12/9999','%d/%m/%Y')
FROM STAGE.STG_FACTURAS_FCT FCT
INNER JOIN ODS_HC_CLIENTES CLI ON CASE WHEN TRIM(CUSTOMER_ID)!=NULL THEN TRIM(CUSTOMER_ID) ELSE 999999999 END=ID_CLIENTE
INNER JOIN ODS_DM_CICLOS_FACTURACION CF ON CASE WHEN(BILL_CYCLE)<>'' THEN UPPER(TRIM(BILL_CYCLE)) ELSE 'DESCONOCIDO' END=CF.DE_CICLO_FACTURACION
INNER JOIN ODS_DM_METODOS_PAGO MP ON CASE WHEN(BILL_METHOD)<>'' THEN UPPER(TRIM(BILL_METHOD)) ELSE 'DESCONOCIDO' END=MP.DE_METODO_PAGO
;

COMMIT;    ANALYZE TABLE ODS_HC_FACTURAS;





