USE STAGE;

/*EN PRINCIPIO TODO EN ORDEN. A VISTA DE LOS RESULTADOS HABRÁ QUE HACER DIMENSIONES DE AGENTES Y DEPARTAMENTOS */

SELECT COUNT(*) TOTAL_CONTACTOS
, SUM(CASE WHEN LENGTH(TRIM(ID))<>'' THEN 1 ELSE 0 END) TOTAL_ID
, COUNT(DISTINCT CASE WHEN LENGTH((ID))<>'' THEN ID ELSE 0 END) TOTAL_DISTINTOS_ID
, SUM(CASE WHEN LENGTH(TRIM(PHONE_NUMBER))<>'' THEN 1 ELSE 0 END) TOTAL_PHONE_NUMBER
, COUNT(DISTINCT CASE WHEN LENGTH((PHONE_NUMBER))<>'' THEN PHONE_NUMBER ELSE 0 END) TOTAL_DISTINTOS_PHONE_NUMBER
, SUM(CASE WHEN LENGTH(TRIM(START_DATETIME))<>'' THEN 1 ELSE 0 END) TOTAL_START_DATETIME
, COUNT(DISTINCT CASE WHEN LENGTH((START_DATETIME))<>'' THEN START_DATETIME ELSE 0 END) TOTAL_DISTINTOS_START_DATETIME
, SUM(CASE WHEN LENGTH(TRIM(END_DATETIME))<>'' THEN 1 ELSE 0 END) TOTAL_END_DATETIME
, COUNT(DISTINCT CASE WHEN LENGTH((END_DATETIME))<>'' THEN END_DATETIME ELSE 0 END) TOTAL_DISTINTOS_END_DATETIME
, SUM(CASE WHEN LENGTH(TRIM(SERVICE))<>'' THEN 1 ELSE 0 END) TOTAL_SERVICE
, COUNT(DISTINCT CASE WHEN LENGTH((SERVICE))<>'' THEN SERVICE ELSE 0 END) TOTAL_DISTINTOS_SERVICE
, SUM(CASE WHEN LENGTH(TRIM(FLG_TRANSFER))<>'' THEN 1 ELSE 0 END) TOTAL_FLG_TRANSFER
, COUNT(DISTINCT CASE WHEN LENGTH((FLG_TRANSFER))<>'' THEN FLG_TRANSFER ELSE 0 END) TOTAL_DISTINTOS_FLG_TRANSFER
, SUM(CASE WHEN LENGTH(TRIM(AGENT))<>'' THEN 1 ELSE 0 END) TOTAL_AGENT
, COUNT(DISTINCT CASE WHEN LENGTH((AGENT))<>'' THEN AGENT ELSE 0 END) TOTAL_DISTINTOS_AGENT
FROM STG_CONTACTOS_IVR;