USE ODS;


DROP TABLE IF EXISTS ODS_HC_LLAMADAS;/*BASICAMENTE IGUAL QUE EL MODELO BASE EXCEPTUANDO LA OMISION DE FLG_SALIDA Y FLG_ENTRADA,
PUES NO TENEMOS DATOS DE PARTIDA SUFICIENTES*/
CREATE TABLE ODS_HC_LLAMADAS
(ID_LLAMADA INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY   
,TELEFONO_LLAMADA BIGINT(20)  
,ID_CLIENTE INT(11)
,FC_INICIO_LLAMADA DATETIME
,FC_FIN_LLAMADA DATETIME
,ID_DEPARTAMENTO_CC INT(10) UNSIGNED
,FLG_TRANSFERIDO TINYINT(1)
,ID_AGENTE INT(10) UNSIGNED
,FC_INSERT DATETIME
,FC_MODIFICACION DATETIME
);

DROP TABLE IF EXISTS ODS_DM_AGENTES_CC;
CREATE TABLE ODS_DM_AGENTES_CC
(ID_AGENTE_CC INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY
,DE_AGENTE VARCHAR(512)
,FC_INSERT DATETIME
,FC_MODIFICACION DATETIME
);

DROP TABLE IF EXISTS ODS_DM_DEPARTAMENTOS_CC;
CREATE TABLE ODS_DM_DEPARTAMENTOS_CC
(ID_DEPARTAMENTO_CC INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY
,DE_DEPARTAMENTO_CC VARCHAR(512)
,FC_INSERT DATETIME
,FC_MODIFICACION DATETIME
);

