USE ODS;

SELECT COUNT(*) TOTAL_ORDENES
,SUM(CASE WHEN LENGTH(TRIM(ID))!='' THEN 1 ELSE 0 END) NUMERO_ID
,COUNT(DISTINCT CASE WHEN LENGTH(TRIM(ID))!='' THEN ID ELSE 0 END) NUMERO_DISTINTOS_ID
,SUM(CASE WHEN LENGTH(TRIM(`ORDER`))!='' THEN 1 ELSE 0 END) NUMERO_ORDER
,COUNT(DISTINCT CASE WHEN LENGTH(`ORDER`)!='' THEN `ORDER` ELSE 0 END) NUMERO_DISTINTOS_ORDER
,SUM(CASE WHEN LENGTH(TRIM(PHASE))!='' THEN 1 ELSE 0 END) NUMERO_PHASE
,COUNT(DISTINCT CASE WHEN LENGTH(TRIM(PHASE))!='' THEN PHASE ELSE 0 END) NUMERO_DISTINTOS_PHASE
,SUM(CASE WHEN LENGTH(TRIM(AGENT))!='' THEN 1 ELSE 0 END) NUMERO_AGENT
,COUNT(DISTINCT CASE WHEN LENGTH(TRIM(AGENT))!='' THEN AGENT ELSE 0 END) NUMERO_DISTINTOS_AGENT
,SUM(CASE WHEN LENGTH(TRIM(START_DT))!='' THEN 1 ELSE 0 END) NUMERO_START_DT
,COUNT(DISTINCT CASE WHEN LENGTH(TRIM(START_DT))!='' THEN START_DT ELSE 0 END) NUMERO_DISTINTOS_START_DT
,SUM(CASE WHEN LENGTH(END_DT)!='' THEN 1 ELSE 0 END) NUMERO_END_DT
,COUNT(DISTINCT CASE WHEN LENGTH(TRIM(END_DT))!='' THEN END_DT ELSE 0 END) NUMERO_DISTINTOS_END_DT
FROM STAGE.STG_ORDERS_CRM;

SELECT * FROM STAGE.STG_ORDERS_CRM

/*360067 ORDENES, SEGUN LOS RESULTADOS VA A HABER QUE SACAR DIMENSION DE TIPOS ORDER, AGENTES Y FASE*/