USE STAGE; 

/*17558*/

SELECT COUNT(*) TOTAL_REGISTROS
, SUM(CASE WHEN LENGTH(TRIM(CUSTOMER_ID))<>'' THEN 1 ELSE 0 END) TOTAL_CUSTOMER_ID
, COUNT(DISTINCT CASE WHEN LENGTH((CUSTOMER_ID))<>'' THEN CUSTOMER_ID ELSE 0 END) TOTAL_DISTINTOS_CUSTOMER_ID
, SUM(CASE WHEN LENGTH(TRIM(FIRST_NAME))<>'' THEN 1 ELSE 0 END) TOTAL_FIRST_NAME
, COUNT(DISTINCT CASE WHEN LENGTH((FIRST_NAME))<>'' THEN FIRST_NAME ELSE 0 END) TOTAL_DISTINTOS_FIRST_NAME
, SUM(CASE WHEN LENGTH(TRIM(LAST_NAME))<>'' THEN 1 ELSE 0 END) TOTAL_LAST_NAME
, COUNT(DISTINCT CASE WHEN LENGTH((LAST_NAME))<>'' THEN LAST_NAME ELSE 0 END) TOTAL_DISTINTOS_LAST_NAME
, SUM(CASE WHEN LENGTH(TRIM(IDENTIFIED_DOC))<>'' THEN 1 ELSE 0 END) TOTAL_IDENTIFIED_DOC
, COUNT(DISTINCT CASE WHEN LENGTH((IDENTIFIED_DOC))<>'' THEN IDENTIFIED_DOC ELSE 0 END) TOTAL_DISTINTOS_IDENTIFIED_DOC
, SUM(CASE WHEN LENGTH(TRIM(GENDER))<>'' THEN 1 ELSE 0 END) TOTAL_GENDER
, COUNT(DISTINCT CASE WHEN LENGTH((GENDER))<>'' THEN GENDER ELSE 0 END) TOTAL_DISTINTOS_GENDER
, SUM(CASE WHEN LENGTH(TRIM(CITY))<>'' THEN 1 ELSE 0 END) TOTAL_CITY
, COUNT(DISTINCT CASE WHEN LENGTH((CITY))<>'' THEN CITY ELSE 0 END) TOTAL_DISTINTOS_CITY
, SUM(CASE WHEN LENGTH(TRIM(ADDRESS))<>'' THEN 1 ELSE 0 END) TOTAL_ADDRESS
, COUNT(DISTINCT CASE WHEN LENGTH((ADDRESS))<>'' THEN ADDRESS ELSE 0 END) TOTAL_DISTINTOS_ADDRESS
, SUM(CASE WHEN LENGTH(TRIM(POSTAL_CODE))<>'' THEN 1 ELSE 0 END) TOTAL_POSTAL_CODE
, COUNT(DISTINCT CASE WHEN LENGTH((POSTAL_CODE))<>'' THEN POSTAL_CODE ELSE 0 END) TOTAL_DISTINTOS_POSTAL_CODE
, SUM(CASE WHEN LENGTH(TRIM(STATE))<>'' THEN 1 ELSE 0 END) TOTAL_STATE
, COUNT(DISTINCT CASE WHEN LENGTH((STATE))<>'' THEN STATE ELSE 0 END) TOTAL_DISTINTOS_STATE
, SUM(CASE WHEN LENGTH(TRIM(COUNTRY))<>'' THEN 1 ELSE 0 END) TOTAL_COUNTRY
, COUNT(DISTINCT CASE WHEN LENGTH((COUNTRY))<>'' THEN COUNTRY ELSE 0 END) TOTAL_DISTINTOS_COUNTRY
, SUM(CASE WHEN LENGTH(TRIM(PHONE))<>'' THEN 1 ELSE 0 END) TOTAL_PHONE
, COUNT(DISTINCT CASE WHEN LENGTH((PHONE))<>'' THEN PHONE ELSE 0 END) TOTAL_DISTINTOS_PHONE
, SUM(CASE WHEN LENGTH(TRIM(EMAIL))<>'' THEN 1 ELSE 0 END) TOTAL_EMAIL
, COUNT(DISTINCT CASE WHEN LENGTH((EMAIL))<>'' THEN EMAIL ELSE 0 END) TOTAL_DISTINTOS_EMAIL
, SUM(CASE WHEN LENGTH(TRIM(BIRTHDAY))<>'' THEN 1 ELSE 0 END) TOTAL_BIRTHDAY
, COUNT(DISTINCT CASE WHEN LENGTH(BIRTHDAY)<>'' THEN BIRTHDAY ELSE 0 END) TOTAL_DISTINTOS_BIRTHDAY
, SUM(CASE WHEN LENGTH(TRIM(PROFESION))<>'' THEN 1 ELSE 0 END) TOTAL_PROFESION
, COUNT(DISTINCT CASE WHEN LENGTH((PROFESION))<>'' THEN PROFESION ELSE 0 END) TOTAL_DISTINTOS_PROFESION
, SUM(CASE WHEN LENGTH(TRIM(COMPANY))<>'' THEN 1 ELSE 0 END) TOTAL_COMPANY
, COUNT(DISTINCT CASE WHEN LENGTH((COMPANY))<>'' THEN COMPANY ELSE 0 END) TOTAL_DISTINTOS_COMPANY
FROM STG_CLIENTES_CRM