USE STAGE;

/*# TOTAL_PRODUCTOS, TOTAL_PRODUCT_ID, TOTAL_DISTINTOS_PRODUCT_ID, TOTAL_CUSTOMER_ID, TOTAL_DISTINTOS_CUSTOMER_ID, TOTAL_PRODUCT_NAME, 
        '78495',        '78495',            '78495',                    '78495',            '8001',                 '78495',  
TOTAL_DISTINTOS_PRODUCT_NAME, TOTAL_ACCESS_POINT, TOTAL_DISTINTOS_ACCESS_POINT, TOTAL_CANAL, TOTAL_DISTINTOS_CANAL, 
           '6',                      '78274',           '78275',                       '78274',            '5',   
TOTAL_AGENT_CODE, TOTAL_DISTINTOS_AGENT_CODE, TOTAL_START_DATE, TOTAL_DISTINTOS_START_DATE, TOTAL_INSTALL_DATE, TOTAL_DISTINTOS_INSTALL_DATE, 
    '42630',               '7970',                  '78495',               '8035',                 '75363',                    '75360',      
TOTAL_END_DATE, TOTAL_DISTINTOS_END_DATE, TOTAL_END_DATE, TOTAL_DISTINTOS_END_DATE, TOTAL_PRODUCT_CITY, TOTAL_DISTINTOS_PRODUCT_CITY, TOTAL_PRODUCT_ADDRESS,
   '46684',          '8001',                     '46684',        '46683',                '78274',                '82',                        '78274', 
TOTAL_DISTINTOS_PRODUCT_ADDRESS, TOTAL_PRODUCT_POSTAL_CODE, TOTAL_DISTINTOS_PRODUCT_POSTAL_CODE, TOTAL_PRODUCT_STATE, TOTAL_DISTINTOS_PRODUCT_STATE,  
   '77037',                                '78274',                           '274',                  '78090',                    '4',                  
TOTAL_PRODUCT_COUNTRY, TOTAL_DISTINTOS_PRODUCT_COUNTRY
        '78274',                  '2'                                                                                                                     */


/*A VISTA DE LOS RESULTADOS HABRÁ QUE HACER DIMENSIONES DE NOMBRE_PRODUCTOS Y CANALES*/
	
SELECT COUNT(*) TOTAL_PRODUCTOS
, SUM(CASE WHEN LENGTH(TRIM(PRODUCT_ID))<>'' THEN 1 ELSE 0 END) TOTAL_PRODUCT_ID
, COUNT(DISTINCT CASE WHEN LENGTH((PRODUCT_ID))<>'' THEN PRODUCT_ID ELSE 0 END) TOTAL_DISTINTOS_PRODUCT_ID
, SUM(CASE WHEN LENGTH(TRIM(CUSTOMER_ID))<>'' THEN 1 ELSE 0 END) TOTAL_CUSTOMER_ID
, COUNT(DISTINCT CASE WHEN LENGTH((CUSTOMER_ID))<>'' THEN CUSTOMER_ID ELSE 0 END) TOTAL_DISTINTOS_CUSTOMER_ID
, SUM(CASE WHEN LENGTH(TRIM(PRODUCT_NAME))<>'' THEN 1 ELSE 0 END) TOTAL_PRODUCT_NAME
, COUNT(DISTINCT CASE WHEN LENGTH((PRODUCT_NAME))<>'' THEN PRODUCT_NAME ELSE 0 END) TOTAL_DISTINTOS_PRODUCT_NAME
, SUM(CASE WHEN LENGTH(TRIM(ACCESS_POINT))<>'' THEN 1 ELSE 0 END) TOTAL_ACCESS_POINT
, COUNT(DISTINCT CASE WHEN LENGTH((ACCESS_POINT))<>'' THEN ACCESS_POINT ELSE 0 END) TOTAL_DISTINTOS_ACCESS_POINT
, SUM(CASE WHEN LENGTH(TRIM(CHANNEL))<>'' THEN 1 ELSE 0 END) TOTAL_CANAL
, COUNT(DISTINCT CASE WHEN LENGTH((CHANNEL))<>'' THEN CHANNEL ELSE 0 END) TOTAL_DISTINTOS_CANAL
, SUM(CASE WHEN LENGTH(TRIM(AGENT_CODE))<>'' THEN 1 ELSE 0 END) TOTAL_AGENT_CODE
, COUNT(DISTINCT CASE WHEN LENGTH((AGENT_CODE))<>'' THEN CUSTOMER_ID ELSE 0 END) TOTAL_DISTINTOS_AGENT_CODE
, SUM(CASE WHEN LENGTH(TRIM(START_DATE))<>'' THEN 1 ELSE 0 END) TOTAL_START_DATE
, COUNT(DISTINCT CASE WHEN LENGTH((START_DATE))<>'' THEN START_DATE ELSE 0 END) TOTAL_DISTINTOS_START_DATE
, SUM(CASE WHEN LENGTH(TRIM(INSTALL_DATE))<>'' THEN 1 ELSE 0 END) TOTAL_INSTALL_DATE
, COUNT(DISTINCT CASE WHEN LENGTH((INSTALL_DATE))<>'' THEN INSTALL_DATE ELSE 0 END) TOTAL_DISTINTOS_INSTALL_DATE
, SUM(CASE WHEN LENGTH(TRIM(END_DATE))<>'' THEN 1 ELSE 0 END) TOTAL_END_DATE
, COUNT(DISTINCT CASE WHEN LENGTH((CUSTOMER_ID))<>'' THEN CUSTOMER_ID ELSE 0 END) TOTAL_DISTINTOS_END_DATE
, SUM(CASE WHEN LENGTH(TRIM(END_DATE))<>'' THEN 1 ELSE 0 END) TOTAL_END_DATE
, COUNT(DISTINCT CASE WHEN LENGTH((END_DATE))<>'' THEN END_DATE ELSE 0 END) TOTAL_DISTINTOS_END_DATE
, SUM(CASE WHEN LENGTH(TRIM(PRODUCT_CITY))<>'' THEN 1 ELSE 0 END) TOTAL_PRODUCT_CITY
, COUNT(DISTINCT CASE WHEN LENGTH((PRODUCT_CITY))<>'' THEN PRODUCT_CITY ELSE 0 END) TOTAL_DISTINTOS_PRODUCT_CITY
, SUM(CASE WHEN LENGTH(TRIM(PRODUCT_ADDRESS))<>'' THEN 1 ELSE 0 END) TOTAL_PRODUCT_ADDRESS
, COUNT(DISTINCT CASE WHEN LENGTH((PRODUCT_ADDRESS))<>'' THEN PRODUCT_ADDRESS ELSE 0 END) TOTAL_DISTINTOS_PRODUCT_ADDRESS
, SUM(CASE WHEN LENGTH(TRIM(PRODUCT_POSTAL_CODE))<>'' THEN 1 ELSE 0 END) TOTAL_PRODUCT_POSTAL_CODE
, COUNT(DISTINCT CASE WHEN LENGTH(PRODUCT_POSTAL_CODE)<>'' THEN PRODUCT_POSTAL_CODE ELSE 0 END) TOTAL_DISTINTOS_PRODUCT_POSTAL_CODE
, SUM(CASE WHEN LENGTH(TRIM(PRODUCT_STATE))<>'' THEN 1 ELSE 0 END) TOTAL_PRODUCT_STATE
, COUNT(DISTINCT CASE WHEN LENGTH((PRODUCT_STATE))<>'' THEN PRODUCT_STATE ELSE 0 END) TOTAL_DISTINTOS_PRODUCT_STATE
, SUM(CASE WHEN LENGTH(TRIM(PRODUCT_COUNTRY))<>'' THEN 1 ELSE 0 END) TOTAL_PRODUCT_COUNTRY
, COUNT(DISTINCT CASE WHEN LENGTH((PRODUCT_COUNTRY))<>'' THEN PRODUCT_COUNTRY ELSE 0 END) TOTAL_DISTINTOS_PRODUCT_COUNTRY
FROM STG_PRODUCTOS_CRM;